from PyQt5 import QtCore, QtGui, QtWidgets
from math import *
from PyQt5.QtWidgets import QMessageBox

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(260, 387)
        MainWindow.setStyleSheet("background-color:#473d3d")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_result = QtWidgets.QLabel(self.centralwidget)
        self.label_result.setGeometry(QtCore.QRect(20, 0, 260, 41))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(11)
        self.label_result.setFont(font)
        self.label_result.setStyleSheet("color: #F0FFF0;\n"
"background-color:#473d3d")
        self.label_result.setObjectName("label_result")
        self.bt_0 = QtWidgets.QPushButton(self.centralwidget)
        self.bt_0.setGeometry(QtCore.QRect(80, 310, 40, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.bt_0.setFont(font)
        self.bt_0.setStyleSheet("background-color: #1c1818;\n"
"color: rgb(255, 255, 255);")
        self.bt_0.setObjectName("bt_0")
        self.bt_2 = QtWidgets.QPushButton(self.centralwidget)
        self.bt_2.setGeometry(QtCore.QRect(80, 250, 40, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.bt_2.setFont(font)
        self.bt_2.setStyleSheet("background-color: #1c1818;\n"
"color: rgb(255, 255, 255);")
        self.bt_2.setObjectName("bt_2")
        self.bt_6 = QtWidgets.QPushButton(self.centralwidget)
        self.bt_6.setGeometry(QtCore.QRect(140, 190, 40, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.bt_6.setFont(font)
        self.bt_6.setStyleSheet("background-color: #1c1818;\n"
"color: rgb(255, 255, 255);")
        self.bt_6.setObjectName("bt_6")
        self.bt_4 = QtWidgets.QPushButton(self.centralwidget)
        self.bt_4.setGeometry(QtCore.QRect(20, 190, 40, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.bt_4.setFont(font)
        self.bt_4.setStyleSheet("background-color: #1c1818;\n"
"color: rgb(255, 255, 255);")
        self.bt_4.setObjectName("bt_4")
        self.bt_7 = QtWidgets.QPushButton(self.centralwidget)
        self.bt_7.setGeometry(QtCore.QRect(20, 130, 40, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.bt_7.setFont(font)
        self.bt_7.setStyleSheet("background-color: #1c1818;\n"
"color: rgb(255, 255, 255);")
        self.bt_7.setObjectName("bt_7")
        self.bt_1 = QtWidgets.QPushButton(self.centralwidget)
        self.bt_1.setGeometry(QtCore.QRect(20, 250, 40, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.bt_1.setFont(font)
        self.bt_1.setStyleSheet("background-color: #1c1818;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.bt_1.setObjectName("bt_1")
        self.bt_8 = QtWidgets.QPushButton(self.centralwidget)
        self.bt_8.setGeometry(QtCore.QRect(80, 130, 40, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.bt_8.setFont(font)
        self.bt_8.setStyleSheet("background-color: #1c1818;\n"
"color: rgb(255, 255, 255);")
        self.bt_8.setObjectName("bt_8")
        self.bt_3 = QtWidgets.QPushButton(self.centralwidget)
        self.bt_3.setGeometry(QtCore.QRect(140, 250, 40, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.bt_3.setFont(font)
        self.bt_3.setStyleSheet("background-color: #1c1818;\n"
"color: rgb(255, 255, 255);")
        self.bt_3.setObjectName("bt_3")
        self.bt_5 = QtWidgets.QPushButton(self.centralwidget)
        self.bt_5.setGeometry(QtCore.QRect(80, 190, 40, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.bt_5.setFont(font)
        self.bt_5.setStyleSheet("background-color: #1c1818;\n"
"color: rgb(255, 255, 255);")
        self.bt_5.setObjectName("bt_5")
        self.bt_9 = QtWidgets.QPushButton(self.centralwidget)
        self.bt_9.setGeometry(QtCore.QRect(140, 130, 40, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.bt_9.setFont(font)
        self.bt_9.setStyleSheet("background-color: #1c1818;\n"
"color: rgb(255, 255, 255);")
        self.bt_9.setObjectName("bt_9")
        self.bt_total = QtWidgets.QPushButton(self.centralwidget)
        self.bt_total.setGeometry(QtCore.QRect(200, 310, 40, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.bt_total.setFont(font)
        self.bt_total.setStyleSheet("color: rgb(11, 255, 11);\n"
"background-color: rgb(16, 45, 13);")
        self.bt_total.setObjectName("bt_total")
        self.bt_tochka = QtWidgets.QPushButton(self.centralwidget)
        self.bt_tochka.setGeometry(QtCore.QRect(140, 310, 40, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.bt_tochka.setFont(font)
        self.bt_tochka.setStyleSheet("background-color: #1c1818;\n"
"color: rgb(11, 255, 11);")
        self.bt_tochka.setObjectName("bt_tochka")
        self.bt_clear = QtWidgets.QPushButton(self.centralwidget)
        self.bt_clear.setGeometry(QtCore.QRect(20, 310, 40, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.bt_clear.setFont(font)
        self.bt_clear.setStyleSheet("background-color: #1c1818;\n"
"color: rgb(11, 255, 11);")
        self.bt_clear.setObjectName("bt_clear")
        self.bt_umn = QtWidgets.QPushButton(self.centralwidget)
        self.bt_umn.setGeometry(QtCore.QRect(200, 130, 40, 48))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.bt_umn.setFont(font)
        self.bt_umn.setStyleSheet("background-color: #1c1818;\n"
"color: rgb(11, 255, 11);")
        self.bt_umn.setObjectName("bt_umn")
        self.bt_del = QtWidgets.QPushButton(self.centralwidget)
        self.bt_del.setGeometry(QtCore.QRect(200, 60, 40, 48))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.bt_del.setFont(font)
        self.bt_del.setStyleSheet("background-color: #1c1818;\n"
"color: rgb(11, 255, 11);")
        self.bt_del.setObjectName("bt_del")
        self.bt_stepen = QtWidgets.QPushButton(self.centralwidget)
        self.bt_stepen.setGeometry(QtCore.QRect(140, 60, 40, 48))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.bt_stepen.setFont(font)
        self.bt_stepen.setStyleSheet("background-color: #1c1818;\n"
"color: rgb(11, 255, 11);")
        self.bt_stepen.setObjectName("bt_stepen")
        self.bt_koren = QtWidgets.QPushButton(self.centralwidget)
        self.bt_koren.setGeometry(QtCore.QRect(80, 60, 40, 48))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.bt_koren.setFont(font)
        self.bt_koren.setStyleSheet("background-color: #1c1818;\n"
"color: rgb(11, 255, 11);")
        self.bt_koren.setObjectName("bt_koren")
        self.bt_procent = QtWidgets.QPushButton(self.centralwidget)
        self.bt_procent.setGeometry(QtCore.QRect(20, 60, 40, 48))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.bt_procent.setFont(font)
        self.bt_procent.setStyleSheet("background-color: #1c1818;\n"
"color: rgb(11, 255, 11);")
        self.bt_procent.setObjectName("bt_procent")
        self.bt_plus = QtWidgets.QPushButton(self.centralwidget)
        self.bt_plus.setGeometry(QtCore.QRect(200, 190, 40, 48))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.bt_plus.setFont(font)
        self.bt_plus.setStyleSheet("background-color: #1c1818;\n"
"color: rgb(11, 255, 11);")
        self.bt_plus.setObjectName("bt_plus")
        self.bt_minus = QtWidgets.QPushButton(self.centralwidget)
        self.bt_minus.setGeometry(QtCore.QRect(200, 250, 40, 48))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.bt_minus.setFont(font)
        self.bt_minus.setStyleSheet("background-color: #1c1818;\n"
"color: rgb(11, 255, 11);")
        self.bt_minus.setObjectName("bt_minus")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


        self.add_function()
        self.is_equal = False
        self.init_graf()
        


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.label_result.setText(_translate("MainWindow", ""))
        self.bt_0.setText(_translate("MainWindow", "0"))
        self.bt_2.setText(_translate("MainWindow", "2"))
        self.bt_6.setText(_translate("MainWindow", "6"))
        self.bt_4.setText(_translate("MainWindow", "4"))
        self.bt_7.setText(_translate("MainWindow", "7"))
        self.bt_1.setText(_translate("MainWindow", "1"))
        self.bt_8.setText(_translate("MainWindow", "8"))
        self.bt_3.setText(_translate("MainWindow", "3"))
        self.bt_5.setText(_translate("MainWindow", "5"))
        self.bt_9.setText(_translate("MainWindow", "9"))
        self.bt_total.setText(_translate("MainWindow", "="))
        self.bt_tochka.setText(_translate("MainWindow", "."))
        self.bt_clear.setText(_translate("MainWindow", "C"))
        self.bt_umn.setText(_translate("MainWindow", "*"))
        self.bt_del.setText(_translate("MainWindow", "/"))
        self.bt_stepen.setText(_translate("MainWindow", "**"))
        self.bt_koren.setText(_translate("MainWindow", "√"))
        self.bt_procent.setText(_translate("MainWindow", "%"))
        self.bt_plus.setText(_translate("MainWindow", "+"))
        self.bt_minus.setText(_translate("MainWindow", "-"))

#Functions


    def add_function(self):
        self.bt_0.clicked.connect(lambda: self.write_number(self.bt_0.text()))
        self.bt_1.clicked.connect(lambda: self.write_number(self.bt_1.text()))
        self.bt_2.clicked.connect(lambda: self.write_number(self.bt_2.text()))
        self.bt_3.clicked.connect(lambda: self.write_number(self.bt_3.text()))
        self.bt_4.clicked.connect(lambda: self.write_number(self.bt_4.text()))
        self.bt_5.clicked.connect(lambda: self.write_number(self.bt_5.text()))
        self.bt_6.clicked.connect(lambda: self.write_number(self.bt_6.text()))
        self.bt_7.clicked.connect(lambda: self.write_number(self.bt_7.text()))
        self.bt_8.clicked.connect(lambda: self.write_number(self.bt_8.text()))
        self.bt_9.clicked.connect(lambda: self.write_number(self.bt_9.text()))


        self.bt_minus.clicked.connect(lambda: self.write_number(self.bt_minus.text()))
        self.bt_plus.clicked.connect(lambda: self.write_number(self.bt_plus.text()))
        self.bt_del.clicked.connect(lambda: self.write_number(self.bt_del.text()))
        self.bt_umn.clicked.connect(lambda: self.write_number(self.bt_umn.text()))
        self.bt_koren.clicked.connect(lambda: self.write_number(self.bt_koren.text()))
        self.bt_stepen.clicked.connect(lambda: self.write_number(self.bt_stepen.text()))
        self.bt_procent.clicked.connect(lambda: self.write_number(self.bt_procent.text()))
        self.bt_clear.clicked.connect(lambda: self.clean_result(self.bt_clear.text()))
        self.bt_tochka.clicked.connect(lambda: self.write_number(self.bt_tochka.text()))

        self.bt_total.clicked.connect(self.result)



    def write_number(self, number):
        if self.label_result.text() == '0000':
            self.label_result.setText(number)
        else:
            self.label_result.setText(self.label_result.text() + number)


    def result(self):
        res = eval(self.label_result.text())
        self.label_result.setText('' + str(res))
        self.is_equal = True

    def clean_result(self, text):
        self.label_result.setText('')
        

    def init_graf(self):
        MainWindow.setWindowTitle('Calc')
        MainWindow.setWindowIcon(QtGui.QIcon('calc.ico'))
        MainWindow.setFixedSize(260, 387)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
