from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1170, 750)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1170, 750))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(24)
        self.frame.setFont(font)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.dibiloader = QtWidgets.QLabel(self.frame)
        self.dibiloader.setGeometry(QtCore.QRect(480, 20, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(24)
        self.dibiloader.setFont(font)
        self.dibiloader.setObjectName("dibiloader")
        self.photo = QtWidgets.QLabel(self.frame)
        self.photo.setGeometry(QtCore.QRect(50, 250, 591, 461))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(22)
        self.photo.setFont(font)
        self.photo.setStyleSheet("border: 1px solid black;\n"
"")
        self.photo.setObjectName("photo")
        self.info = QtWidgets.QLabel(self.frame)
        self.info.setGeometry(QtCore.QRect(660, 250, 491, 461))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(22)
        self.info.setFont(font)
        self.info.setStyleSheet("border: 1px solid black\n"
"")
        self.info.setObjectName("info")
        self.url = QtWidgets.QLineEdit(self.frame)
        self.url.setGeometry(QtCore.QRect(60, 100, 551, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.url.setFont(font)
        self.url.setStyleSheet("border: 1px solid black")
        self.url.setObjectName("url")
        self.set_url = QtWidgets.QPushButton(self.frame)
        self.set_url.setGeometry(QtCore.QRect(640, 100, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.set_url.setFont(font)
        self.set_url.setObjectName("set_url")
        self.set_folder = QtWidgets.QPushButton(self.frame)
        self.set_folder.setGeometry(QtCore.QRect(640, 170, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.set_folder.setFont(font)
        self.set_folder.setObjectName("set_folder")
        self.folder = QtWidgets.QLabel(self.frame)
        self.folder.setGeometry(QtCore.QRect(60, 170, 551, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.folder.setFont(font)
        self.folder.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    border: 1px solid black\n"
"}")
        self.folder.setText("")
        self.folder.setObjectName("folder")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.dibiloader.setText(_translate("MainWindow", "YT Dibiloader"))
        self.photo.setText(_translate("MainWindow", "Cover photo"))
        self.info.setText(_translate("MainWindow", "Info about video"))
        self.set_url.setText(_translate("MainWindow", "Check"))
        self.set_folder.setText(_translate("MainWindow", "Set"))
